import { JSDOM } from 'jsdom';
console.error('step: fetching the page');
const page = await (await fetch('http://127.0.0.1:3000/admin')).text();
console.error('step: page bytes', page.length);
const script = await (await fetch('http://127.0.0.1:3000/admin/app.js')).text();
console.error('step: app.js bytes', script.length);
console.error('step: building jsdom');
const dom = new JSDOM(page, { runScripts: 'outside-only', url: 'https://localhost/admin', pretendToBeVisual: true });
console.error('step: readyState', dom.window.document.readyState);
await new Promise((resolve) => setTimeout(resolve, 50));
console.error('step: readyState after tick', dom.window.document.readyState);
console.error('step: evaluating client');
dom.window.eval(script);
console.error('step: client evaluated');
await new Promise((resolve) => setTimeout(resolve, 50));
console.error('step: done');
process.exit(0);
